services:
  auth-db:
    image: mongo:5.0.2
    restart: always
    container_name: Auth_DB
    env_file:
      - ../../packages/auth/.env
    ports:
      - "27017:27017"
    volumes:
      - db:/data/db
    networks:
      - backend_network

  todo-db:
    image: mongo:5.0.2
    restart: always
    container_name: Todo_DB
    env_file:
      - ../../packages/to-do/.env
    ports:
      - "27018:27017"
    volumes:
      - todo_db:/data/db
    networks:
      - backend_network

  rabbitmq:
    image: rabbitmq:3-management
    container_name: RabbitMQ
    ports:
      - "5672:5672"
      - "15672:15672"
    env_file:
      - ../rabbitmq/rabbitmq.env
    networks:
      - backend_network

  api:
    container_name: API_Gateway
    build:
      context: ../../packages/api
      dockerfile: Dockerfile
    depends_on:
      - auth-db
    env_file:
      - ../../packages/api/.env
    ports:
      - "3000:3000"
    volumes:
      - ../../packages/api:/app
      - /app/node_modules
    networks:
      - backend_network

  auth:
    container_name: Auth_Service
    build:
      context: ../../packages/auth
      dockerfile: Dockerfile
    depends_on:
      - auth-db
    env_file:
      - ../../packages/auth/.env
      - ../rabbitmq/rabbitmq.env
    ports:
      - "3010:3010"
    volumes:
      - ../../packages/auth:/app
      - /app/node_modules
    networks:
      - backend_network

  todo:
    container_name: Todo_Service
    build:
      context: ../../packages/to-do
      dockerfile: Dockerfile
    depends_on:
      - todo-db
      - auth-db
    env_file:
      - ../../packages/to-do/.env
      - ../rabbitmq/rabbitmq.env
    ports:
      - "3020:3020"
    volumes:
      - ../../packages/to-do:/app
      - /app/node_modules
    networks:
      - backend_network

  dashboard:
    container_name: Dashboard
    build:
      context: ../../packages/frontend
      dockerfile: Dockerfile
    depends_on:
      - auth-db
    env_file:
      - ../../packages/frontend/.env
    ports:
      - "5173:5173"
    volumes:
      - ../../packages/frontend:/app
      - /app/node_modules
    networks:
      - backend_network

networks:
  backend_network:
    driver: bridge

volumes:
  db:
  todo_db:
